[package]
name = "lab1"
version = "1.0.0"
edition = "2021"
authors = ["Pavel Grigorenko <311639@niuitmo.ru>"]

[dependencies]
indicatif = { version = "0.17", features = ["rayon"] }
itertools = "0.10"
rand = "0.8"
rayon = "1.7"
